services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - 1883:1883 #default mqtt port
      - 9001:9001 #default mqtt port for websockets
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data:rw
      - ./mqtt/log:/mosquitto/log:rw
    restart: unless-stopped

  db:
    image: postgres:16
    restart: always
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready", "-U", "loremipsum", "-d", "loremipsum"]
      interval: 3s
      retries: 10
      start_period: 30s
    environment:
      POSTGRES_DB: loremipsum
      POSTGRES_USER: loremipsum
      POSTGRES_PASSWORD: loremipsum
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5455:5432

  ntp:
    image: cturra/ntp:latest
    container_name: ntp-server
    restart: unless-stopped
    ports:
      - "123:123/udp"
    cap_add:
      - SYS_TIME
    environment:
      # Upstream servers your Docker host will sync with
      - NTP_SERVERS=time.google.com,pool.ntp.org

  worker:
      build:
        context: .
        dockerfile: Dockerfile.worker
      container_name: swim_worker
      restart: unless-stopped
      depends_on:
        db:
          condition: service_healthy
        mqtt5:
          condition: service_started
      environment:
        DATABASE_URL: postgres://loremipsum:loremipsum@db:5432/loremipsum
        MQTT_URL: mqtt://mqtt5:1883

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: swim_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      mqtt5:
        condition: service_started
    environment:
      DATABASE_URL: postgres://loremipsum:loremipsum@db:5432/loremipsum
      VITE_MQTT_WS_URL: ws://192.168.0.2:9001

volumes:
  db_data:
